[package]
name = "triplestore"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fjall = { path = "../../" }
serde_json = "1.0.99"
serde = "1.0.193"
