[package]
name = "structured"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fjall = { path = "../../" }
rmp-serde = "1.1.2"
serde = "1.0.193"
