[workspace]
resolver = "2"
members = ["lsm-tree", "fjall"]

[workspace.package]
edition = "2021"
rust-version = "1.74.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["database", "lsmt", "lsm", "rocksdb", "leveldb"]
categories = ["data-structures", "database-implementations", "algorithms"]
homepage = "https://github.com/marvin-j97/fjall"
