name: CI

on:
  #  TODO: remove
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  test_stable:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ runner.os }}-cargo
          workspaces: >
                      . -> target
                      examples/actix-kv -> target
      - name: Build
        run: cargo build -v
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test -v -- --nocapture
      - name: Build KV example
        run: cargo build
        working-directory: examples/actix-kv
      - name: Test KV example
        run: cargo test
        working-directory: examples/actix-kv